name: Sprawdzanie_wersji_Pythona

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sprawdzanie_wersji_pythona:
    runs-on: ubuntu-latest

    steps:
      - name: Wyświetl_wersję_pythona
        run: python --version
