name: Sprawdzanie_wersji_Pythona_i_testowanie_pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testowanie_pylint:
    runs-on: ubuntu-latest

    steps:
      - name: v2
        uses: actions/checkout@v2

      - name: instalacja_bibliotek
        run: |
          pip install flask
          pip install pylint

      - name: uruchamianie Pylint
        run: pylint app.py



  sprawdzanie_wersji_pythona:
    runs-on: ubuntu-latest

    steps:
      - name: Wyświetl_wersję_pythona
        run: python --version
        

